apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
{{ include "cosi-driver-nutanix.resource.annotations" . | indent 4 }}
  labels:
{{ include "cosi-driver-nutanix.resource.labels" . | indent 4 }}
  name: objectstorage-provisioner
  namespace: {{ .Release.Namespace }}
spec:
  minReadySeconds: 30
  progressDeadlineSeconds: 600
  replicas: {{ .Values.replicas }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
{{ include "cosi-driver-nutanix.resource.labels" . | indent 6 }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
{{ include "cosi-driver-nutanix.resource.annotations" . | indent 8 }}
      labels:
{{ include "cosi-driver-nutanix.resource.labels" . | indent 8 }}
    spec:
      imagePullSecrets: {{ .Values.provisioner.image.pullSecrets }}
      containers:
      - image: {{ include "cosi-driver-nutanix.driverImageName" . }}
        imagePullPolicy: {{ .Values.provisioner.image.pullPolicy }}
        name: cosi-driver-nutanix
        volumeMounts:
        - mountPath: /var/lib/cosi
          name: socket
        - mountPath: /cosi
          name: {{ include "cosi-driver-nutanix.configVolumeName" . }}
      - name: objectstorage-provisioner-sidecar
        image: {{ include "cosi-driver-nutanix.sidecarImageName" .}}
        imagePullPolicy: {{ .Values.objectstorageProvisionerSidecar.image.pullPolicy }}
        args:
          - "--v={{ .Values.objectstorageProvisionerSidecar.logLevel }}"
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
        - mountPath: /var/lib/cosi
          name: socket
      serviceAccountName: objectstorage-provisioner-sa
      volumes:
      - name: socket
        emptyDir: {}
      - name: {{ include "cosi-driver-nutanix.configVolumeName" . }}
        secret:
          secretName: {{ include "cosi-driver-nutanix.configSecretName" . }}
