{{- if .Values.configuration.create }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "cosi-driver-nutanix.configSecretName" .}}
  labels:
{{ include "cosi-driver-nutanix.resource.labels" . | indent 4 }}
  annotations:
{{ include "cosi-driver-nutanix.resource.annotations" . | indent 4 }}
data:
  config.yaml: {{ toString .Values.configuration.data | b64enc }}
{{- end }}
