# Default values for cosi-driver-nutanix.
nameOverride: ""
fullnameOverride: ""

# cosi-driver-nutanix sidecar image.
image:
  registry: ghcr.io
  repository: nutanix-cloud-native/cosi-driver-nutanix
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
  pullPolicy: IfNotPresent

# Secret used by the cosi-driver-nutanix sidecar for objects management.
secret:
  enabled: true
  # Nutanix Object Store instance endpoint, eg. "https://10.51.142.82:443".
  endpoint: ""
  # Admin IAM Access key to be used for Nutanix Objects.
  access_key: ""
  # Admin IAM Secret key to be used for Nutanix Objects.
  secret_key: ""
  # PC Credentials.
  pc_ip: ""
  pc_port: "9440"
  pc_username: "admin"
  pc_password: ""
  # Account Name is a displayName identifier Prefix for Nutanix.
  # Objects to ensure that multiple requests for the same account
  # result in only one access token being created.
  # (Default_Prefix: ntnx-cosi-iam-user)
  account_name: "ntnx-cosi-iam-user"

tls:
  # If insecure is set to true, an insecure connection will be made with
  # the S3 endpoint. (Certs will not be used)
  insecure: false
  # If secretName is provided, value of rootCAs
  # will be ignored and taken from the secret.
  secretName: ""
  # Base64 encoded content of the root certificate authority file
  # Example, rootCas: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURWRENDQWp5Z0F3SUJBZ0lSQUxMbVpYNERvclRrSFp6TlZoQStSWVV3RFFZSktvWklodmNOQVFFTEJRQXcKRnpFVk1CTUdBMVVFQ2hNTVRuVjBZVzVwZUNCSmJtTXVNQ0FYRFRJMU1ERXlOekE0TURVME5Wb1lEekl5TURRdwpOekF6TURnd05UUTFXakFYTVJVd0V3WURWUVFLRXd4T2RYUmhibWw0SUVsdVl5NHdnZ0VpTUEwR0NTcUdTSWIzCkRRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRRFh2R0JTZkFCeXQxVkN2QXVhRFRocTdIK0psSzhIZTh6Y2pxRDcKREdlNkRjMWpxOW43K2VONlgrY1RUODVkS1BoYWpqUHA5TmM0ZzFIVDBqZldIRDRRSGhna1MxMk55MFdybXFxcgpxeDhGY3V6aGF6ODlCRnlhSTN0T0NCeDc1eVplOXphTlNPQm9LSnFyZXUybUFqZkk4TE03akZsL2NPTjY4S2Q5Ci9iNmc4OSsyRk1FMGdGcTJwM21hYkdYR1ZlckZBSzBnN1R1ZmZoV0t5S0wvQjllcXVaMk03Q21oQU83d2Ewa28KQ25RSlkzWHZOazRPVWViN05YQmRwc3dwV0Q3ODlyWFNzU01ieGFTOVptRHJxdkI3QTFJbFdqd0VVVnp4WW5QdwoyMW1pcWZaNXFiMnAzZ1p0U1RiRE9xbWcwbDl5ZnZ3SXJvYUdLTUxyUkNLMFErSWpBZ01CQUFHamdaZ3dnWlV3CkRnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3SFFZRFZSME9CQllFRlBFOWg4NXEKaDUzcktickJSZCtWblVHdUF4cEtNRk1HQTFVZEVRUk1NRXFDSW5KcGJYVnlkUzV3Y21semJTMWpaVzUwY21GcwpMbU5zZFhOMFpYSXViRzlqWVd5Q0pDb3VjbWx0ZFhKMUxuQnlhWE50TFdObGJuUnlZV3d1WTJ4MWMzUmxjaTVzCmIyTmhiREFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBZDN3Tjk4eGFUSnFCR0UyajBxb1NRaHFNTmI1Tm1CRGEKQ3AvUHQwbXdsQUptdjJwZXR6M09ONWVkdDMveUM4MXZFdldmVCs0R3BNLzZqQUhjWTlyWitYUUErWmtTbmpzRwppdEFMZ1NMcTc3dkRZUlRIQVhmc1dQSDJEWTE0MElTNk9xcVR0TFBMdWtIenV4NXVSMkxIMXVnZ1U1c0FSczVsCkVCaTF6bndzblN4cktmcVBPdXJ0NG9TZ1c3Rm91Z3FpYU9pSytWa20rMUZ0eWJWbE1YSDF3NVRrZVBGSy94N0IKT2tpS3BQb0FMbVB5MVkyQnh2YnB4UVlMalpFRk1Ld0lvN0cyMHBsOW9wRm50Q0JzNkdjWTdRTmVzVllLYXdWMQp6UUVzYkpZQnVoajFYZ2p6UngrNmFsMkZqZjJORk4zSTJhQ0tRWjlvTUZzZzBSL00wYmlCakE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg=="
  rootCAs: ""

# COSI central controller specifications.
cosiController:
  enabled: true
  logLevel: 5
  image:
    registry: gcr.io
    repository: k8s-staging-sig-storage/objectstorage-controller
    tag: v20250110-a29e5f6
    pullPolicy: Always

# COSI sidecar specifications.
objectstorageProvisionerSidecar:
  logLevel: 5
  image:
    registry: gcr.io
    repository: k8s-staging-sig-storage/objectstorage-sidecar/objectstorage-sidecar
    tag: v20221117-v0.1.0-22-g0e67387
    pullPolicy: Always
